name = "jagogoclaw"
pages_build_output_dir = "./dist"
compatibility_date = "2025-01-01"
account_id = "999662db57e14ce2af4e731aadaadfae"

# Database Cloudflare D1
[[d1_databases]]
binding = "DB"
database_name = "jagogoclaw-db"
database_id = "7e948d5c-b81e-4fb6-93e2-67e81ff7e39f"
